---
# tasks file for roles/provisioning
 - name: Provisoning Rhel Instances in AWS
   local_action:
     module: ec2
     key_name: '{{ aws_instance_keypair }}'
     group_id: '{{ aws_instance_security_group }}'
     instance_type: '{{ aws_instance_type }}'
     image: '{{ aws_instance_image }}'
     vpc_subnet_id: '{{ aws_instance_subnet_ids }}'
     region: '{{ aws_instance_region }}'
     instance_tags: 
         Name: '{{ aws_instance_tag_Name }}'
         Type: '{{ aws_instance_tag_Type }}'
         Environment: '{{ aws_instance_tag_Environment }}'
         AccountingCode: '{{ aws_account_code }}'
         BU: '{{ aws_bu }}'
     assign_public_ip: yes
     wait: true
     count: '{{ aws_instance_count }}'
     volumes:
     - device_name: /dev/xvda
       device_type: gp2
       volume_size: '{{ aws_instance_volume_size }}'
       delete_on_termination: true
   register: aws_new_instance



