---
# tasks file for roles/termination
- name: Getting the facts of OLD VM.
  local_action:
     module: ec2_remote_facts
     aws_access_key: '{{ aws_access_key }}'
     aws_secret_key: '{{ aws_secret_key }}'
     region: '{{ aws_instance_region }}'
     filters:
        instance-state-name: running
        "tag:terminate_vm_tag": '{{ aws_instance_termination_tag }}'
  register: ec2_facts_old_vms

- name: Terminating the OLD instances
  local_action:
     module: ec2
     aws_access_key: '{{ aws_access_key }}'
     aws_secret_key: '{{ aws_secret_key }}'
     region: '{{ aws_instance_region }}'
     wait: yes
     wait_timeout: 500
     instance_ids: "{{ item.id }}"
     state: 'absent'
  with_items: '{{ ec2_facts_old_vms.instances }}'
